# ========================
# APPLICATION
# ========================
app:
    myVar: ${VAR:defaultValue}
    cloneDirectory: ${CLONE_DIRECTORY}
    cloneFrequency: 0 * * * *
    cloneRepositories:
      - http://models.interlis.ch
      #- http://models.geo.admin.ch
    peerRepositories:
      - https://geo.so.ch/models