
logging.level.org.apache.cayenne.log.JdbcEventLogger: INFO

app:
    myVar: ${VAR:defaultValue}
    ilicachedb: ${ILICACHEDB:/Users/stefan/tmp/ilicache/ilicachedb}
    cloneDirectory: ${CLONE_DIRECTORY:/Users/stefan/tmp/ilicache/}
    cloneRepositories:
      - http://models.interlis.ch
      #- http://models.geo.admin.ch
    peerRepositories:
      - https://geo.so.ch/models

user:
  cloneFrequency: 0 * * * *
  cloneRespositories:
    - http://models.interlis.ch
  peerRepositories:
    - https://geo.so.ch/models  
    
