logging.level.root: ${ROOT_LOGLEVEL:INFO}
logging.level.org.apache.cayenne.log.JdbcEventLogger: ${CAYENNE_LOGLEVEL:DEBUG}

# https://github.com/spring-projects/spring-boot/wiki/Spring-Boot-2.4-Release-Notes#default-servlet-registration
# https://stackoverflow.com/questions/64822250/illegalstateexception-after-upgrading-web-app-to-spring-boot-2-4
server.servlet.register-default-servlet: true

app:
    myVar: ${VAR:defaultValue}
    ilicachedb: ${ILICACHEDB:/Users/stefan/tmp/ilicache/ilicachedb} #/tmp/

user:
  iliSite:
    name: ${ILISITE_NAME:interlis-model-repositories-mirror}
    title: ${ILISITE_TITLE:INTERLIS model repositories mirror}
    shortDescription: ${ILISITE_SHORT_DESCRIPTION:A mirror of INTERLIS model repositories}
    owner: ${ILISITE_OWNER:https://geo.so.ch}
    technicalContact: ${ILISITE_TECHNICAL_CONTACT:mailto:agi@bd.so.ch} 
    furtherInformation: ${ILISITE_FURTHER_INFORMATION:}
  cloneDirectory: ${CLONE_DIRECTORY:/Users/stefan/tmp/ilicache/}
  cloneCronExpression: ${CLONE_CRON_EXPRESSION:0 0/2 * * * ?} #"0 0 2 * * ?"
  cloneOnStartup: ${CLONE_ON_STARTUP:false}
  cloneRepositories: ${CLONE_REPOSITORIES:http://models.interlis.ch}
  #peerRepositories: ${PEER_REPOSITORIES:http://models.interlis.ch}
   
