logging.level.root: ${ROOT_LOGLEVEL:INFO}
logging.level.org.apache.cayenne.log.JdbcEventLogger: ${CAYENNE_LOGLEVEL:DEBUG}

# https://github.com/spring-projects/spring-boot/wiki/Spring-Boot-2.4-Release-Notes#default-servlet-registration
# https://stackoverflow.com/questions/64822250/illegalstateexception-after-upgrading-web-app-to-spring-boot-2-4
server.servlet.register-default-servlet: true

app:
    myVar: ${VAR:defaultValue}
    ilicachedb: ${ILICACHEDB:/Users/stefan/tmp/ilicache/ilicachedb}

user:
  iliSite:
    name: cache.models.geo.so.ch
    title: INTERLIS repositories cache
    shortDescription: Cache of some INTERLIS repositories.
    owner: https://geo.so.ch
    technicalContact: mailto:agi@bd.so.ch
    furtherInformation: https://geo.so.ch
  cloneDirectory: ${CLONE_DIRECTORY:/Users/stefan/tmp/ilicache/}
  cloneCronExpression: "0 0/2 * * * ?" #"0 0 2 * * ?"
  cloneOnStartup: false
  cloneRepositories:
    - http://models.interlis.ch
  peerRepositories:
    - https://geo.so.ch/models  
