
logging.level.org.apache.cayenne.log.JdbcEventLogger: ${CAYENNE_LOGLEVEL:INFO}

app:
    myVar: ${VAR:defaultValue}
    ilicachedb: ${ILICACHEDB:/Users/stefan/tmp/ilicache/ilicachedb.mv.db}

user:
  iliSite:
    name: cache.models.geo.so.ch
    title: INTERLIS repositories cache
    shortDescription: Cache of some INTERLIS repositories.
    owner: https://geo.so.ch
    technicalContact: mailto:agi@bd.so.ch
    furtherInformation: https://geo.so.ch
  cloneDirectory: ${CLONE_DIRECTORY:/Users/stefan/tmp/ilicache/}
  cloneFrequency: 0 * * * *
  cloneRespositories:
    - http://models.interlis.ch
  peerRepositories:
    - https://geo.so.ch/models  
    
