# ========================
# APPLICATION
# ========================
app:
    myVar: ${VAR:defaultValue}
    cloneDirectory: ${CLONE_DIRECTORY}
    repositories:
      - http://models.interlis.ch
      - http://models.geo.admin.ch
    peerRepositories:
      - https://geo.so.ch/models