package ch.so.agi.ilicache.cayenne.auto;

import java.io.IOException;
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;
import java.time.LocalDateTime;

import org.apache.cayenne.BaseDataObject;
import org.apache.cayenne.exp.Property;

/**
 * Class _Clonerepository was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _Clonerepository extends BaseDataObject {

    private static final long serialVersionUID = 1L; 

    public static final String T_ID_PK_COLUMN = "T_ID";

    public static final Property<String> ANAME = Property.create("aname", String.class);
    public static final Property<LocalDateTime> LASTRUN = Property.create("lastrun", LocalDateTime.class);
    public static final Property<LocalDateTime> LASTSUCCESSFULRUN = Property.create("lastsuccessfulrun", LocalDateTime.class);
    public static final Property<String> URL = Property.create("url", String.class);

    protected String aname;
    protected LocalDateTime lastrun;
    protected LocalDateTime lastsuccessfulrun;
    protected String url;


    public void setAname(String aname) {
        beforePropertyWrite("aname", this.aname, aname);
        this.aname = aname;
    }

    public String getAname() {
        beforePropertyRead("aname");
        return this.aname;
    }

    public void setLastrun(LocalDateTime lastrun) {
        beforePropertyWrite("lastrun", this.lastrun, lastrun);
        this.lastrun = lastrun;
    }

    public LocalDateTime getLastrun() {
        beforePropertyRead("lastrun");
        return this.lastrun;
    }

    public void setLastsuccessfulrun(LocalDateTime lastsuccessfulrun) {
        beforePropertyWrite("lastsuccessfulrun", this.lastsuccessfulrun, lastsuccessfulrun);
        this.lastsuccessfulrun = lastsuccessfulrun;
    }

    public LocalDateTime getLastsuccessfulrun() {
        beforePropertyRead("lastsuccessfulrun");
        return this.lastsuccessfulrun;
    }

    public void setUrl(String url) {
        beforePropertyWrite("url", this.url, url);
        this.url = url;
    }

    public String getUrl() {
        beforePropertyRead("url");
        return this.url;
    }

    @Override
    public Object readPropertyDirectly(String propName) {
        if(propName == null) {
            throw new IllegalArgumentException();
        }

        switch(propName) {
            case "aname":
                return this.aname;
            case "lastrun":
                return this.lastrun;
            case "lastsuccessfulrun":
                return this.lastsuccessfulrun;
            case "url":
                return this.url;
            default:
                return super.readPropertyDirectly(propName);
        }
    }

    @Override
    public void writePropertyDirectly(String propName, Object val) {
        if(propName == null) {
            throw new IllegalArgumentException();
        }

        switch (propName) {
            case "aname":
                this.aname = (String)val;
                break;
            case "lastrun":
                this.lastrun = (LocalDateTime)val;
                break;
            case "lastsuccessfulrun":
                this.lastsuccessfulrun = (LocalDateTime)val;
                break;
            case "url":
                this.url = (String)val;
                break;
            default:
                super.writePropertyDirectly(propName, val);
        }
    }

    private void writeObject(ObjectOutputStream out) throws IOException {
        writeSerialized(out);
    }

    private void readObject(ObjectInputStream in) throws IOException, ClassNotFoundException {
        readSerialized(in);
    }

    @Override
    protected void writeState(ObjectOutputStream out) throws IOException {
        super.writeState(out);
        out.writeObject(this.aname);
        out.writeObject(this.lastrun);
        out.writeObject(this.lastsuccessfulrun);
        out.writeObject(this.url);
    }

    @Override
    protected void readState(ObjectInputStream in) throws IOException, ClassNotFoundException {
        super.readState(in);
        this.aname = (String)in.readObject();
        this.lastrun = (LocalDateTime)in.readObject();
        this.lastsuccessfulrun = (LocalDateTime)in.readObject();
        this.url = (String)in.readObject();
    }

}
